export const FETCH_STAFF_LIST_START = 'FETCH_STAFF_LIST_START';
export const FETCH_STAFF_LIST_SUCCESS = 'FETCH_STAFF_LIST_SUCCESS';
export const FETCH_STAFF_LIST_FAIL = 'FETCH_STAFF_LIST_FAIL';

export const FETCH_EMPLOYEE_START = 'FETCH_EMPLOYEE_START';
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS';
export const FETCH_EMPLOYEE_FAIL = 'FETCH_EMPLOYEE_FAIL';

export const SEND_COMMENT_START = 'SEND_COMMENT_START';
export const SEND_COMMENT_SUCCESS = 'SEND_COMMENT_SUCCESS';
export const SEND_COMMENT_FAIL = 'SEND_COMMENT_FAIL';
